on:
  schedule:
    - cron: "0 10 * * 1-6"
  workflow_dispatch:  

jobs:
  descargar_sumario:
    name: Descargar el sumario del d√≠a
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Ejecutar el script de descarga del sumario
        run: |
          cd scripts
          chmod +x ./sumario_del_dia.sh
          ./sumario_del_dia.sh

      - name: Commit y Push de los cambios
        uses: Smart-Transportation/push@v1.3
        with:
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          
